raevyxSpawnWeight = 1
raevyxMinGroupSize = 1
raevyxMaxGroupSize = 2
raevyxAdditionalBiomes = []
stegonautSpawnWeight = 5
stegonautMinGroupSize = 1
stegonautMaxGroupSize = 4
stegonautAdditionalBiomes = []
cindervaneSpawnWeight = 3
cindervaneMinGroupSize = 1
cindervaneMaxGroupSize = 3
cindervaneAdditionalBiomes = []
nulljawSpawnWeight = 2
nulljawMinGroupSize = 1
nulljawMaxGroupSize = 2
nulljawAdditionalBiomes = []
ignivorusSpawnWeight = 1
ignivorusMinGroupSize = 1
ignivorusMaxGroupSize = 2
ignivorusAdditionalBiomes = []
